name: Android Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        
    - name: Install dependencies
      run: |
        cd frontend-mobile
        npm install
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Install Capacitor CLI
      run: |
        cd frontend-mobile
        npm install -g @capacitor/cli
        
    - name: Sync Capacitor project
      run: |
        cd frontend-mobile
        npx cap sync android
        
    - name: Build with Gradle
      run: |
        cd frontend-mobile/android
        chmod +x gradlew
        ./gradlew assembleDebug
      
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: frontend-mobile/android/app/build/outputs/apk/debug/app-debug.apk